name: outofstock_env
dependencies:
  # The python interpreter version.
  # Currently Azure ML only supports 3.5.2 and later.
- python=3.6.5
- nb_conda==2.2.0
- tensorflow-gpu==1.12.0
- pip:
  - python-dotenv==0.10.1
  - Pillow==6.0.0
  - wget==3.2
  - matplotlib==3.0.3
  - azureml-sdk[notebooks, contrib]==1.0.23
